// Class =========================================================

### 
GET http://localhost:3003/class/all

###
GET http://localhost:3003/class/Classe 3

###
POST http://localhost:3003/class/create
Content-Type: application/json

{
  "nameClass": "Classe 3",
  "responsible": "Gabriel"
}

###
DELETE http://localhost:3003/class/Classe 3

// ================================================================

// Students =======================================================

###
POST http://localhost:3003/students/Classe 3
Content-Type: application/json

{
  "firstName": "Test 1",
  "lastName": "Test 2",
  "participation": 1
}

###
PUT http://localhost:3003/students/Classe 3/3feef23a-ce3d-409b-ad0e-1024316de7dc
Content-Type: application/json

{
  "firstName": "Test 3",
  "lastName": "Test 33",
  "participation": 10
}

###
DELETE http://localhost:3003/students/Classe 3/346b28d1-921a-4a72-8bfd-6adb574fb046

// ================================================================